### ISSUE TITLE
Your linker_pc.exe causes models to spawn on 0,0,0 with default angles

### ISSUE THREAD

**Issue by RealViruz** [T-Maxxx/iw3linker#3]
First of all thanks for starting this Project, its very usefull to alot of cod devs out there.

Im compiling a map with one custom model and a couch model, however when i use your compiler the models spawn on coordinates 0,0,0 and with default angles, not with the position and angles which are set in the .map file

I tried it on multiple devices and the error appeared each time i replaced linker_pc.exe with your one.

Hope you fix it,
Greetings,
Viruz

**Comment by T-Maxxx** [comment]
I did not changed any compiling logic/code. Everything must work as always. Can you post some screenshots? I don't understand how xmodel position during compiling can affect position inside map during compilation using other tool.

**Comment by RealViruz** [comment]
Map in Radiant (custom logo on right side)
![mapsourcecustomlogoright](https://cloud.githubusercontent.com/assets/29149952/26738331/09a05412-47ce-11e7-9bd3-bfd933aa78f3.png)
Stock linkerpc ingame result
![stocklinkerpc](https://cloud.githubusercontent.com/assets/29149952/26738334/09c1423a-47ce-11e7-82f3-a18b6e6423f0.jpg)
Stock linkerpc ingame result
![stocklinkerpc2](https://cloud.githubusercontent.com/assets/29149952/26738335/09c361be-47ce-11e7-86db-88e6c0ecfb7d.jpg)
Map in radiant (stock model on left platform)
![stockmodel on leftside](https://cloud.githubusercontent.com/assets/29149952/26738338/09cc2c54-47ce-11e7-8d2b-938c9c7474d9.png)
Your linkerpc exe ingame result
![yourlinkerpc 2](https://cloud.githubusercontent.com/assets/29149952/26738337/09cc365e-47ce-11e7-9286-02fb695ff4a6.jpg)
Your linkerpc exe ingame result
![yourlinkerpc](https://cloud.githubusercontent.com/assets/29149952/26738332/09c148a2-47ce-11e7-969f-4a1639568d4b.jpg)
Your linkerpc exe ingame result 2
![yourlinkerpc2](https://cloud.githubusercontent.com/assets/29149952/26738336/09c8c7f8-47ce-11e7-9dff-30f5d00dceba.jpg)

There are no diffrences in compiling bsp/reflections or .ff between your and the stock linker_pc.exe no additional errors nothing. The couch is placed on the left platform (in radiant image) and the custom model far away from spawn (right object in radiant screen).
Also i tried it on my laptop where i do not run into the g_stream out of memory to make sure that this doesnt happen due to missing memory or idk (as it looks like u just removed the error call function).

**Comment by T-Maxxx** [comment]
Nope, all I did is just patched [memory allocation](https://github.com/T-Maxxx/iw3linker/blob/master/src/database/db_stream_save.c#L12). Actually, this is the only patch I did so far. Show me models center and its position in Radiant. Then I must know if there are any errors in server/client console shortly after connecting.
Last but not least. Are you sure you compiling exactly this map you show me?

**Comment by T-Maxxx** [comment]
Well, looks like I get exactly same thing you show me with mp_test. I'll take a look into it.
